name: subvfi
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11.4
  - pip=24.0
  - cudatoolkit=11.8
  - pytorch=2.0.1
  - torchvision=0.15.2
  - numpy=1.24.3
  - pip:
    - opencv-python==4.8.0.74
    - imageio==2.31.1
    - omegaconf==2.3.0
    - Pillow==9.4.0
    - tqdm==4.65.0
